# Cloud Build configuration for sGTM deployment (Per-App)
#
# Deploys GTM Server-Side container to Cloud Run for a specific app.
#
# Required substitutions:
#   - _APP_ID: App identifier (ai4su)
#   - _SERVICE_NAME: Cloud Run service name (sgtm-ai4su)
#   - _GTM_CONTAINER_CONFIG: GTM container configuration string
#
# Optional substitutions:
#   - _REGION: Cloud Run region (default: europe-west1)

steps:
  # Step 1: Build sGTM container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${SHORT_SHA}"
      - "-t"
      - "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:latest"
      - "-f"
      - "packages/infra/gtm/Dockerfile.sgtm"
      - "."
    id: "build"

  # Step 2: Push to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${SHORT_SHA}"
    id: "push-sha"
    waitFor: ["build"]

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:latest"
    id: "push-latest"
    waitFor: ["build"]

  # Step 3: Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image"
      - "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${SHORT_SHA}"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--min-instances"
      - "0"
      - "--max-instances"
      - "10"
      - "--memory"
      - "256Mi"
      - "--cpu"
      - "1"
      - "--timeout"
      - "60s"
      - "--concurrency"
      - "80"
      - "--set-env-vars"
      - "CONTAINER_CONFIG=${_GTM_CONTAINER_CONFIG}"
      - "--labels"
      - "app=${_APP_ID},managed-by=cloudbuild"
    id: "deploy"
    waitFor: ["push-sha"]

  # Step 4: Output service URL
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: bash
    args:
      - "-c"
      - |
        echo "==================================="
        echo "sGTM deployed successfully!"
        echo "App: ${_APP_ID}"
        echo "Service: ${_SERVICE_NAME}"
        echo "==================================="
        URL=$(gcloud run services describe ${_SERVICE_NAME} \
          --region=${_REGION} \
          --format='value(status.url)')
        echo "URL: $URL"
        echo ""
        echo "Update SGTM_ENDPOINT_${_APP_ID^^} with this URL."
    waitFor: ["deploy"]

substitutions:
  _REGION: europe-west1
  _APP_ID: ""
  _SERVICE_NAME: ""
  _GTM_CONTAINER_CONFIG: ""

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"

tags:
  - "sgtm"
  - "analytics"
  - "${_APP_ID}"
