# Cloud Build CI/CD Configuration
# Automated deployment pipeline for UI Platform monorepo apps
#
# Features:
# - Separate builds per app with caching
# - Multi-environment support (staging/production)
# - Automated testing before deployment
# - Rollback capability with tagged images
#
# Trigger: git push to main branch
# Branch patterns: main (production), staging/* (staging)

substitutions:
  _APP_NAME: 'web'
  _SERVICE_NAME: 'ui-platform-${_APP_NAME}'
  _REGION: 'europe-west1'
  _ENV: 'production'  # or 'staging'
  _MIN_INSTANCES: '0'  # scale-to-zero for cost optimization
  _MAX_INSTANCES: '10'
  _MEMORY: '512Mi'
  _CPU: '1'
  _TIMEOUT: '300s'

options:
  # Build optimizations
  machineType: 'N1_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY

  # Use Kaniko for Docker builds (faster, cached)
  substitution_option: 'ALLOW_LOOSE'

steps:
  # Step 0: Generate semantic version tag
  - name: 'gcr.io/cloud-builders/git'
    id: 'generate-version'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Generate version from git
        VERSION="v$(date +%Y%m%d)-${SHORT_SHA}"
        echo "$$VERSION" > /workspace/VERSION
        echo "Generated version: $$VERSION"

  # Step 1: Install dependencies and run tests
  - name: 'oven/bun:1'
    id: 'test'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Installing dependencies..."
        bun install

        echo "Running type check..."
        cd apps/${_APP_NAME}
        bun run typecheck || exit 1

        echo "Running linter..."
        bun run lint || exit 1

        # Add unit tests when available
        # bun test || exit 1

        echo "✅ All checks passed"

  # Step 2: Build Docker image with Kaniko (better caching)
  - name: 'gcr.io/kaniko-project/executor:latest'
    id: 'build'
    args:
      - --destination=gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$(cat /workspace/VERSION)
      - --destination=gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_ENV}
      - --destination=gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest
      - --cache=true
      - --cache-ttl=24h
      - --build-arg=APP_NAME=${_APP_NAME}
      - --context=dir:///workspace
      - --dockerfile=packages/infra/Dockerfile
    waitFor: ['test']

  # Step 3: Deploy to Cloud Run (staging or production)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        VERSION=$(cat /workspace/VERSION)

        echo "🚀 Deploying ${_APP_NAME} to ${_ENV}..."
        echo "   Version: $$VERSION"
        echo "   Service: ${_SERVICE_NAME}"
        echo "   Region: ${_REGION}"

        gcloud run deploy ${_SERVICE_NAME} \
          --image=gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$$VERSION \
          --platform=managed \
          --region=${_REGION} \
          --allow-unauthenticated \
          --min-instances=${_MIN_INSTANCES} \
          --max-instances=${_MAX_INSTANCES} \
          --memory=${_MEMORY} \
          --cpu=${_CPU} \
          --timeout=${_TIMEOUT} \
          --set-env-vars="NODE_ENV=production,APP_NAME=${_APP_NAME},DEPLOYED_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
          --tag=$$VERSION \
          --no-traffic \
          --quiet

        # Gradual traffic migration (canary deployment)
        echo "📊 Starting gradual traffic migration..."

        # Send 10% traffic to new version
        gcloud run services update-traffic ${_SERVICE_NAME} \
          --region=${_REGION} \
          --to-revisions=$$VERSION=10 \
          --quiet

        echo "✅ 10% traffic routed to $$VERSION"
        echo "   Monitor for 2 minutes before full rollout"

        # Wait and check error rates
        sleep 120

        # If no critical errors, route 100% traffic
        gcloud run services update-traffic ${_SERVICE_NAME} \
          --region=${_REGION} \
          --to-revisions=$$VERSION=100 \
          --quiet

        echo "✅ Deployment complete!"

        # Get service URL
        SERVICE_URL=$(gcloud run services describe ${_SERVICE_NAME} \
          --region=${_REGION} \
          --format='value(status.url)')

        echo ""
        echo "🌐 Service URL: $$SERVICE_URL"
        echo "📦 Image: gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$$VERSION"
        echo "🏷️  Version: $$VERSION"
    waitFor: ['build']

  # Step 4: Smoke tests
  - name: 'gcr.io/cloud-builders/curl'
    id: 'smoke-test'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        SERVICE_URL=$(gcloud run services describe ${_SERVICE_NAME} \
          --region=${_REGION} \
          --format='value(status.url)')

        echo "Running smoke tests..."

        # Test homepage
        HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" $$SERVICE_URL)
        if [ "$$HTTP_CODE" != "200" ]; then
          echo "❌ Homepage check failed: $$HTTP_CODE"
          exit 1
        fi
        echo "✅ Homepage: 200"

        # Test form page
        HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" $$SERVICE_URL/form)
        if [ "$$HTTP_CODE" != "200" ]; then
          echo "❌ Form page check failed: $$HTTP_CODE"
          exit 1
        fi
        echo "✅ Form page: 200"

        # Test response time
        RESPONSE_TIME=$(curl -o /dev/null -s -w '%{time_total}\n' $$SERVICE_URL)
        echo "⏱️  Response time: $${RESPONSE_TIME}s"

        echo "✅ All smoke tests passed"
    waitFor: ['deploy']

timeout: '1200s'  # 20 minutes total timeout

# Images to push (handled by Kaniko)
images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}'
