# Cloud Build configuration for monorepo apps
# Substitutions:
#   _APP_NAME: Name of the app to build (e.g., "web")
#   _SERVICE_NAME: Cloud Run service name (e.g., "ui-platform-web")
#   _REGION: GCP region (default: "europe-west1")
#   _TAG: Image tag (default: "latest")

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'packages/infra/Dockerfile'
      - '--build-arg'
      - 'APP_NAME=${_APP_NAME}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_TAG}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '.'

  # Push the container images to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_TAG}'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_TAG}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'NODE_ENV=production'

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_TAG}'
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

substitutions:
  _APP_NAME: 'web'
  _SERVICE_NAME: 'ui-platform-web'
  _REGION: 'europe-west1'
  _TAG: 'v1.0.0'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
