# Cloud Build Trigger for Production Deployments
# Automatically deploys to production when code is pushed to main branch

name: ui-platform-production-deploy
description: 'Production deployment for UI Platform apps'

# Trigger on push to main branch
github:
  owner: YOUR_GITHUB_USERNAME  # Replace with your GitHub username/org
  name: UI_platform  # Replace with your repo name
  push:
    branch: '^main$'

# Use the CI/CD configuration
filename: packages/infra/cloudbuild-cicd.yaml

# Production environment substitutions
substitutions:
  _APP_NAME: 'ai4su'
  _ENV: 'production'
  _REGION: 'europe-west1'
  _MIN_INSTANCES: '0'  # Scale-to-zero for cost optimization
  _MAX_INSTANCES: '10'
  _MEMORY: '512Mi'
  _CPU: '1'
  _TIMEOUT: '300s'

# Include files - only trigger if these paths change
includedFiles:
  - 'apps/ai4su/**'
  - 'packages/ui/**'
  - 'packages/config/**'
  - 'packages/types/**'
  - 'packages/utils/**'
  - 'packages/infra/**'
  - 'package.json'

# Ignored files - don't trigger on these
ignoredFiles:
  - '**/*.md'
  - 'docs/**'
  - '.github/**'
  - '**/*.test.ts'
  - '**/*.test.tsx'

# Service account for deployment
# serviceAccount: projects/PROJECT_ID/serviceAccounts/cloud-build@PROJECT_ID.iam.gserviceaccount.com
