# Cloud Build Trigger for sGTM deployment (web)
# Deploys sGTM container to Cloud Run when Dockerfile changes

name: sgtm-deploy-web
description: Deploy sGTM container for web app to Cloud Run

github:
  owner: 0xMoRyuk
  name: UI_platform
  push:
    branch: ^main$

includedFiles:
  - 'packages/infra/gtm/Dockerfile.sgtm'
  - 'packages/infra/gtm/cloudbuild-sgtm.yaml'

filename: packages/infra/gtm/cloudbuild-sgtm.yaml

substitutions:
  _APP_ID: web
  _SERVICE_NAME: sgtm-web
  _GTM_CONTAINER_CONFIG: ${_GTM_CONTAINER_CONFIG_WEB}
  _REGION: europe-west1
