# Cloud Build Trigger for sGTM deployment (designOS_sandbox)
# Deploys sGTM container to Cloud Run when Dockerfile changes

name: sgtm-deploy-sandbox
description: Deploy sGTM container for designOS_sandbox app to Cloud Run

github:
  owner: 0xMoRyuk
  name: UI_platform
  push:
    branch: ^main$

includedFiles:
  - 'packages/infra/gtm/Dockerfile.sgtm'
  - 'packages/infra/gtm/cloudbuild-sgtm.yaml'

filename: packages/infra/gtm/cloudbuild-sgtm.yaml

substitutions:
  _APP_ID: designOS_sandbox
  _SERVICE_NAME: sgtm-sandbox
  _GTM_CONTAINER_CONFIG: ${_GTM_CONTAINER_CONFIG_SANDBOX}
  _REGION: europe-west1
