# Cloud Build Trigger for Staging Deployments
# Automatically deploys to staging when code is pushed to staging/* branches

name: ui-platform-staging-deploy
description: 'Staging deployment for UI Platform apps'

# Trigger on push to staging branches
github:
  owner: YOUR_GITHUB_USERNAME  # Replace with your GitHub username/org
  name: UI_platform  # Replace with your repo name
  push:
    branch: '^staging/.*$'

# Use the CI/CD configuration
filename: packages/infra/cloudbuild-cicd.yaml

# Staging environment substitutions
substitutions:
  _APP_NAME: 'web'
  _ENV: 'staging'
  _REGION: 'europe-west1'
  _MIN_INSTANCES: '0'  # Scale-to-zero for cost optimization
  _MAX_INSTANCES: '3'   # Lower max for staging
  _MEMORY: '512Mi'
  _CPU: '1'
  _TIMEOUT: '300s'

# Include files - only trigger if these paths change
includedFiles:
  - 'apps/web/**'
  - 'packages/ui/**'
  - 'packages/config/**'
  - 'packages/types/**'
  - 'packages/utils/**'
  - 'packages/infra/**'
  - 'package.json'

# Ignored files - don't trigger on these
ignoredFiles:
  - '**/*.md'
  - 'docs/**'
  - '.github/**'

# Service account for deployment
# serviceAccount: projects/PROJECT_ID/serviceAccounts/cloud-build@PROJECT_ID.iam.gserviceaccount.com
